###################################
##                               ##
## - Create API Health Monitor - ##
##                               ##
###################################

- name:  Set Connect URL
  ansible.builtin.set_fact:
    ENVIRONMENT_LONG: "development"
  when: ENVIRONMENT_SHORT == "dev"

- name: Set Connect URL
  ansible.builtin.set_fact:
    ENVIRONMENT_LONG: "staging"
  when: ENVIRONMENT_SHORT == "stg"

- name: Set Connect URL
  ansible.builtin.set_fact:
    ENVIRONMENT_LONG: "production"
  when: ENVIRONMENT_SHORT == "prd"

- name: Template a file to create a Synthetics API Check Monitor
  ansible.builtin.template:
    src: cc_setup/templates/CREATE_SYNTHETICS_API_MONITOR.j2
    dest: "./B2B_SERVICES/lightweight/kong/api_health.{{ENVIRONMENT_SHORT}}.yml"
    # owner: bin
    # group: wheel
    mode: '0644'
  delegate_to: localhost
  delegate_facts: true
  loop: "{{API_HEALTHCHECK_LIST}}"

- name: Deploy Lightweight Monitors to Elastic Project
  local_action: 
    module: shell
    cmd: "SYNTHETICS_API_KEY=VUhCTHFZY0JYdGVaRXRhcEs4NHQ6VUdMcV9Pa3JSN2FraGlzNHQySk1GQQ== npm run push"
    chdir: ./B2B_SERVICES
  delegate_to: localhost
  register: deploy_project_monitors

- name: Debug Variable - deploy_project_monitors
  ansible.builtin.debug:
    var: deploy_project_monitors
  when: debug_variables | bool
