###################################
##                               ##
## - Create Connnector Monitor - ##
##                               ##
###################################

- name: Set encrypted API key
  set_fact:
    api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36643537653130613330303630623261393464626466663665663061383735373865353237383932
          3339303161353335663436383439313662393633613664620a313239323432343834636561666664
          62376131633635636261363033333164353138376462353566353466613439363030343734346433
          3632663465346439650a613664363030613566663561666339646263313331356535376433626362
          36663364343633666538633739356361623233313635313662383432633765656434363333333735
          39346165616430643334353233336437626562393362616361393363356431363637373433626662
          396532373532613835653831386431363233

- name:  Set Connect URL
  ansible.builtin.set_fact:
    CONNECT_URL: "http://connect.dev.shared-services.eu.pvh.cloud/connectors"
    ENVIRONMENT_LONG: "development"
  when: ENVIRONMENT_SHORT == "dev"

- name: Set Connect URL
  ansible.builtin.set_fact:
    CONNECT_URL: "http://connect.stg.shared-services.eu.pvh.cloud/connectors"
    ENVIRONMENT_LONG: "staging"
  when: ENVIRONMENT_SHORT == "stg"

- name: Set Connect URL
  ansible.builtin.set_fact:
    CONNECT_URL: "http://connect.prd.shared-services.eu.pvh.cloud/connectors"
    ENVIRONMENT_LONG: "production"
  when: ENVIRONMENT_SHORT == "prd"

- name: Set Connect URL
  ansible.builtin.set_fact:
    CONNECT_URL: "http://kafka-connect.beta53.kafka.marathon.dcos-eu.pvhcorp.com:8083/connectors"
    ENVIRONMENT_LONG: "staging"
  when: ENVIRONMENT_SHORT == "stg_dcos"

- name: Set Connect URL
  ansible.builtin.set_fact:
    CONNECT_URL: "http://kafka-connect.production53.kafka.marathon.dcos-eu.pvhcorp.com:8083/connectors"
    ENVIRONMENT_LONG: "production"
  when: ENVIRONMENT_SHORT == "prd_dcos"

- name: Get Connector List via API
  block:
    - name: Get Connector List via API
      ansible.builtin.uri:
        url: "{{CONNECT_URL}}"
        method: GET
        headers:
          # Authorization: "{{ FLEET_API_TOKEN }}"
          Content-Type: application/json
        follow_redirects: safe
        force: yes
        remote_src: yes
        status_code: [200]
        return_content: yes
      delegate_to: localhost
      register: get_connector_list

    - name: Debug Variable - get_connector_list
      ansible.builtin.debug:
        var: get_connector_list
      when: debug_variables | bool

- name: Template a file to create a Synthetics Connector Monitor
  ansible.builtin.template:
    src: cc_setup/templates/CREATE_SYNTHETICS_CONNECTOR_MONITOR.j2
    dest: "./B2B_SERVICES/lightweight/confluent/connector.{{ENVIRONMENT_SHORT}}.yml"
    # owner: bin
    # group: wheel
    mode: '0644'
  delegate_to: localhost
  delegate_facts: true
  loop: "{{get_connector_list.json}}"

- name: Deploy Lightweight Monitors to Elastic Project
  local_action: 
    module: shell
    cmd: "SYNTHETICS_API_KEY={{ api_key }} npm run push"
    chdir: ./B2B_SERVICES
  delegate_to: localhost
  register: deploy_project_monitors

- name: Debug Variable - deploy_project_monitors
  ansible.builtin.debug:
    var: deploy_project_monitors
  when: debug_variables | bool
