################################
##                            ##
## - Create ksqlDB Streams  - ##
##                            ##
################################

- name: Create ksqlDB Streams
  include_tasks: tasks/create_stream_block.yaml
  loop: 
    - S_HOMEASSISTANT
    - S_HOMEASSISTANT_MEDIA
    - S_HOMEASSISTANT_ENHANCED
