###################################
##                               ##
## - Create Connnector Monitor - ##
##                               ##
###################################

- name:  Set Connect URL
  ansible.builtin.set_fact:
    CONNECT_URL: "http://connect.dev.shared-services.eu.pvh.cloud/connectors"
    policy_id: 6570a4f0-75a8-11ed-ab8f-a1e0581d79a2
    # policy_id: 27323830-a158-11ed-93a2-9587a59e3cdd
  when: ENVIRONMENT_SHORT == "dev"

- name: Set Connect URL
  ansible.builtin.set_fact:
    # CONNECT_URL: "http://kafka-connect.beta53.kafka.marathon.dcos-eu.pvhcorp.com:8083/connectors"
    CONNECT_URL: "http://connect.stg.shared-services.eu.pvh.cloud/connectors"
    policy_id: 6570a4f0-75a8-11ed-ab8f-a1e0581d79a2
    # policy_id: 684fdc70-a160-11ed-93a2-9587a59e3cdd
  when: ENVIRONMENT_SHORT == "stg"

- name: Set Connect URL
  ansible.builtin.set_fact:
    # CONNECT_URL: "http://kafka-connect.production53.kafka.marathon.dcos-eu.pvhcorp.com:8083/connectors"
    CONNECT_URL: "http://connect.prd.shared-services.eu.pvh.cloud/connectors"
    policy_id: 6570a4f0-75a8-11ed-ab8f-a1e0581d79a2
    # policy_id: 749c3f90-a161-11ed-93a2-9587a59e3cdd
  when: ENVIRONMENT_SHORT == "prd"

- name: Get Connector List via API
  block:
    - name: Get Connector List via API
      ansible.builtin.uri:
        url: "{{CONNECT_URL}}"
        method: GET
        headers:
          # Authorization: "{{ FLEET_API_TOKEN }}"
          Content-Type: application/json
        follow_redirects: safe
        force: yes
        remote_src: yes
        status_code: [200]
        return_content: yes
      delegate_to: localhost
      register: get_connector_list

    - name: Debug Variable - get_connector_list
      ansible.builtin.debug:
        var: get_connector_list
      when: debug_variables | bool

- name: Create Connnector Monitor 
  include_tasks: tasks/create_connector_monitor_block.yaml
  loop: "{{get_connector_list.json}}"
