###################################
##                               ##
## - Create API Health Monitor - ##
##                               ##
###################################


- name: Set encrypted API key
  set_fact:
    api_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      64376236663731343662306330393665323736656265373366373234333465396638313031666164
      3237393765333766386561326565363531386433326562360a326339663635353931393063313934
      33306237323965393230333337363935323661326632373165393562306539353832326631396137
      3737383961376239330a323266376532313539633137656135313062613930303066613061383665
      6133

- name:  Set Connect URL
  ansible.builtin.set_fact:
    ENVIRONMENT_LONG: "development"
  when: ENVIRONMENT_SHORT == "dev"

- name: Set Connect URL
  ansible.builtin.set_fact:
    ENVIRONMENT_LONG: "staging"
  when: ENVIRONMENT_SHORT == "stg"

- name: Set Connect URL
  ansible.builtin.set_fact:
    ENVIRONMENT_LONG: "production"
  when: ENVIRONMENT_SHORT == "prd"

- name: Template a file to create a Synthetics API Check Monitor
  ansible.builtin.template:
    src: cc_setup/templates/CREATE_SYNTHETICS_API_MONITOR.j2
    dest: "./B2B_SERVICES/lightweight/kong/api_health.{{ENVIRONMENT_SHORT}}.yml"
    # owner: bin
    # group: wheel
    mode: '0644'
  delegate_to: localhost
  delegate_facts: true
  loop: "{{API_HEALTHCHECK_LIST}}"

- name: Deploy Lightweight Monitors to Elastic Project
  local_action: 
    module: shell
    cmd: "SYNTHETICS_API_KEY={{ api_key }} npm run push"
    chdir: ./B2B_SERVICES
  delegate_to: localhost
  register: deploy_project_monitors

- name: Debug Variable - deploy_project_monitors
  ansible.builtin.debug:
    var: deploy_project_monitors
  when: debug_variables | bool
