#############################
##                         ##
## - Delete ksqlDB Data  - ##
##                         ##
#############################

- name: Delete ksqlDB Streams
  include_tasks: tasks/delete_tables_block.yaml
  loop: 
    - V_MET_WARNING_II
    - V_HOMEASSISTANT_ENTITY_II
    # - S_HOMEASSISTANT_ENHANCED_II
    # - S_HOMEASSISTANT_MEDIA_II
    # - S_HOMEASSISTANT_II
