##########################
##                      ##
## - Delete Connector - ##
##                      ##
##########################

- name: Delete Connector
  include_tasks: tasks/delete_connector_block.yaml
  no_log: yes
  loop: 
    - JiraSourceConnector_0
    - ServiceNowSourceConnector_0
    # - ElasticsearchSinkConnector_0
