- name: Delete Topics via API
  ansible.builtin.uri:
    url: "{{KAFKA_CLUSTER_URL}}/kafka/v3/clusters/{{KAFKA_CLUSTER_ID}}/topics"
    method: DELETE
    body_format: json
    headers:
      Content-Type: "application/json"
      Authorization: "{{KAFKA_CLOUD_API_TOKEN}}"
    timeout: 90
    force: yes
    status_code: [200]
    return_content: yes
  ignore_errors: yes
  register: delete_topic

- name: Debug Variable - GDeleteet Topics via API
  ansible.builtin.debug:
    var: delete_topic
