
- name: Delete Kafka Connector Monitor via API
  block:

    - name: Delete Kafka Connector Monitor via API
      ansible.builtin.uri:
        url: "{{ FLEET_API_URL }}/package_policies"
        method: GET
        headers:
          Authorization: "{{ FLEET_API_TOKEN }}"
          kbn-xsrf: "kbn-xsrf"
        follow_redirects: yes
        force: true
        status_code: [200]
        return_content: yes
      register: get_package_policies

    - name: Debug Variable - get_package_policies
      ansible.builtin.debug:
        var: get_package_policies
      when: debug_variables | bool

    - name: Create Search Parameters for jmesquery Query
      ansible.builtin.set_fact:
        jmesquery: "items.*.id"
        # jmesquery: "[*].[*].id"
        # jmesquery: "[? name==`DSE`].{id: id}"


    - name: Filter JSON Response with json_query
      ansible.builtin.set_fact:
        delete_package_policies: "{{ get_package_policies.json | json_query(jmesquery) }}"  

    - name: Debug Variable - get_package_policies
      ansible.builtin.debug:
        var: delete_package_policies

# - name: Create Search Parameters For jmesquery Query
#   ansible.builtin.set_fact:
#     # jmesquery: "[*].{id: id}"
#     jmesquery: "[*].{id: id, name: name}"

# - name: Debug Variable - jmesquery
#   ansible.builtin.debug:
#     var: jmesquery
#   when: debug_variables | bool


# - name: Delete Resilio Notification
#   block:

#     - name: Get Resilio Webhook via API
#       ansible.builtin.uri:
#         url: "{{resilio_api_url}}/notifications"
#         method: GET
#         headers:
#           Content-Type: application/json
#           Authorization: "{{resilio_api_token}}"
#         follow_redirects: yes
#         force: true
#         status_code: [200]
#         return_content: yes
#       register: get_notifications

#     - name: Debug Variable - get_notifications
#       ansible.builtin.debug:
#         var: get_notifications
#       when: debug_variables | bool

#     - name: Create Search Parameters for jmesquery Query
#       ansible.builtin.set_fact:
#         jmesquery: "[*].{id: id}"

#     - name: Debug Variable - jmesquery
#       ansible.builtin.debug:
#         var: jmesquery
#       when: debug_variables | bool

#     - name: Filter JSON Response with json_query
#       ansible.builtin.set_fact:
#         delete_notifications: "{{ get_notifications.json | json_query(jmesquery) }}"     

#     - name: Remove Resilio Webhook from Management Console via API
#       uri:
#         url: "{{resilio_api_url}}/notifications/{{item.value}}"
#         method: DELETE
#         return_content: true
#         headers:
#           Content-Type: application/json
#           Authorization: "{{resilio_api_token}}"
#         follow_redirects: true
#         force: true
#         status_code: [200, 204]
#       with_dict: "{{delete_notifications}}"

#   when: "'ResilioManagementConsole' in group_names"      
#   become: true
#   tags:
#     - delete-resilio-notifications












# - name: Delete Kafka Connector Monitor via API
#   ansible.builtin.uri:
#     url: "{{ FLEET_API_URL }}/package_policies/{{packagePolicyId}}"
#     method: POST
#     body_format: json
#     body: "{{ json_body }}"
#     timeout: 90
#     headers:
#       Authorization: "{{ FLEET_API_TOKEN }}"
#       kbn-xsrf: "kbn-xsrf"
#     follow_redirects: yes
#     force: true
#     status_code: [200, 201]
#     return_content: yes
#   register: get_kafka_connector_monitor_list
#   ignore_errors: yes


# - name: Filter JSON Response With json_query
#   ansible.builtin.set_fact:
#     delete_webhooks: "{{ get_webhooks.json | json_query(jmesquery) }}" 

# - name: Debug Variable - json_body
#   ansible.builtin.debug:
#     var: json_body

# - name: Delete Kafka Connector Fleet-Managed Monitor
#   block:

#     - name: Delete Kafka Connector Monitor via API
#       ansible.builtin.uri:
#         url: "{{ FLEET_API_URL }}/package_policies/{{packagePolicyId}}"
#         method: POST
#         body_format: json
#         body: "{{ json_body }}"
#         timeout: 90
#         headers:
#           Authorization: "{{ FLEET_API_TOKEN }}"
#           kbn-xsrf: "kbn-xsrf"
#         follow_redirects: yes
#         force: true
#         status_code: [200, 201]
#         return_content: yes
#       register: deleted_kafka_connector_monitor
#       ignore_errors: yes

#     - name: Debug Variable - Deleted Kafka Connector Monitor
#       ansible.builtin.debug:
#         var: deleted_kafka_connector_monitor


