#############################
##                         ##
## - Drop ksqlDB Tables  - ##
##                         ##
#############################

- name: Drop ksqlDB Tables
  include_tasks: tasks/drop_tables_block.yaml
  no_log: True
  loop: 
    - V_MET_WARNING_II
    - V_HOMEASSISTANT_ENTITY_II

##############################
##                          ##
## - Drop ksqlDB Streams  - ##
##                          ##
##############################

- name: Drop ksqlDB Streams
  include_tasks: tasks/drop_streams_block.yaml
  no_log: True
  loop: 
    - S_HOMEASSISTANT_ENHANCED_II
    - S_HOMEASSISTANT_MEDIA_II
    - S_HOMEASSISTANT_II

#############################
##                         ##
## - Delete Kafka Topics - ##
##                         ##
#############################

- name: Delete Kafka Topics
  include_tasks: tasks/delete_topics_block.yaml
  no_log: True
  loop: 
    - S_HOMEASSISTANT_ENHANCED_II
    - S_HOMEASSISTANT_MEDIA_II
    - S_HOMEASSISTANT_II
    - V_MET_WARNING_II
    - V_HOMEASSISTANT_ENTITY_II
