
- name: Delete Kafka Connector Monitor via API
  block:

    - name: Delete Kafka Connector Monitor via API
      ansible.builtin.uri:
        url: "{{ FLEET_API_URL }}/package_policies"
        method: GET
        headers:
          Authorization: "{{ FLEET_API_TOKEN }}"
          kbn-xsrf: "kbn-xsrf"
        follow_redirects: yes
        force: true
        status_code: [200]
        return_content: yes
      register: get_package_policies

    - name: Debug Variable - get_package_policies
      ansible.builtin.debug:
        var: get_package_policies
      when: debug_variables | bool

    - name: Create Search Parameters for jmesquery Query
      ansible.builtin.set_fact:
        jmesquery: "items[?starts_with(name,`DS - Kafka Connector - TST`)].id"  

    - name: Filter JSON Response with json_query
      ansible.builtin.set_fact:
        delete_package_policies: "{{ get_package_policies.json | to_json | from_json | json_query(jmesquery) }}"  

    - name: Debug Variable - get_package_policies
      ansible.builtin.debug:
        var: delete_package_policies
