
- name: Get Connector List via API
  ansible.builtin.uri:
    url: "{{CONFLUENT_CLOUD_API_URL}}/connect/v1/environments/{{ENVIRONMENT_ID}}/clusters/{{CLUSTER_ID}}/connectors?expand=status"
    method: GET
    headers:
      Content-Type: "application/json"
      Authorization: "{{CONFLUENT_CLOUD_API_TOKEN}}"
    timeout: 90
    force: yes
    status_code: [200]
    return_content: yes
  ignore_errors: yes
  register: connector_list

- name: Debug Variable - Get Connector List via API
  ansible.builtin.debug:
    var: connector_list

# - name: Create Search Parameters For jmesquery Query
#   ansible.builtin.set_fact:
#     jmesquery: "[*].{id: id}"

#   - name: Debug Variable - jmesquery
#     ansible.builtin.debug:
#       var: jmesquery
#     when: debug_variables | bool

#   - name: Filter JSON Response With json_query
#     ansible.builtin.set_fact:
#       delete_webhooks: "{{ get_webhooks.json | json_query(jmesquery) }}"