- name: Get Topics via API
  ansible.builtin.uri:
    url: "{{KAFKA_CLUSTER_URL}}/kafka/v3/clusters/{{KAFKA_CLUSTER_ID}}/topics"
    method: GET
    body_format: json
    headers:
      Content-Type: "application/json"
    url_username: "{{KAFKA_CLUSTER_USERNAME}}"
    url_password: "{{KAFKA_CLUSTER_PASSWORD}}"
    timeout: 90
    force: yes
    status_code: [200]
    return_content: yes
  ignore_errors: yes
  register: get_topic_list

- name: Debug Variable - Get Topics via API
  ansible.builtin.debug:
    var: get_topic_list
