---
# tasks file for cc_setup
- name: Create Initial ksqlDB Setup
  import_tasks: create.yaml
  tags: create_ksqlDB_init_setup

- name: Create Initial ksqlDB Setup
  import_tasks: delete.yaml
  tags: delete_ksqlDB_init_setup

- name: Create Connector
  import_tasks: create_connector.yaml
  tags: create_connector

- name: Delete Connector
  import_tasks: delete_connector.yaml
  tags: delete_connector