---
# tasks file for cc_setup
- name: Create Initial ksqlDB Setup
  import_tasks: create.yaml
  tags: create_ksqlDB_init_setup

- name: Create Initial ksqlDB Setup
  import_tasks: delete.yaml
  tags: delete_ksqlDB_init_setup

- name: Create Connector
  import_tasks: create_connector.yaml
  tags: create_connector

- name: Delete Connector
  import_tasks: delete_connector.yaml
  tags: delete_connector

- name: Get Topics
  import_tasks: get_topics.yaml
  tags: get_topics

- name: Delete Topic
  import_tasks: delete_topic.yaml
  tags: delete_topic

- name: Get Connector List
  import_tasks: get_connector_list_expansions.yaml
  tags: get_connector_list

- name: Update Connector
  import_tasks: update_connector.yaml
  tags: update_connector

- name: Pause Connector
  import_tasks: pause_connector.yaml
  tags: paused_connector

- name: Resume Connector
  import_tasks: resume_connector.yaml
  tags: resumed_connector