---
# tasks file for cc_setup
- name: Create Initial ksqlDB Setup
  import_tasks: create.yaml
  tags: create_ksqlDB_init_setup

- name: Create Initial ksqlDB Setup
  import_tasks: delete.yaml
  tags: delete_ksqlDB_init_setup

- name: Create Connector
  import_tasks: create_connector.yaml
  tags: create_connector

- name: Delete Connector
  import_tasks: delete_connector.yaml
  tags: delete_connector

- name: Get Topics
  import_tasks: get_topics.yaml
  tags: get_topics

- name: Delete Topic
  import_tasks: delete_topic.yaml
  tags: delete_topic

- name: Get Connector List
  import_tasks: get_connector_list_expansions.yaml
  tags: get_connector_list

- name: Update Connector
  import_tasks: update_connector.yaml
  tags: update_connector

- name: Pause Connector
  import_tasks: pause_connector.yaml
  tags: pause_connector

- name: Resume Connector
  import_tasks: resume_connector.yaml
  tags: resume_connector

- name: Status Connector
  import_tasks: status_connector.yaml
  tags: status_connector

- name: Task Status Connector
  import_tasks: task_status_connector.yaml
  tags: task_status_connector

- name: List Connector Plugins
  import_tasks: list_connector_plugins.yaml
  tags: list_connector_plugins

- name: Validate Connector Plugins
  import_tasks: validate_connector_plugins.yaml
  tags: validate_connector_plugins

- name: Create Connector Monitor
  import_tasks: create_connector_monitor.yaml
  tags: create_connector_monitor

- name: Delete Connector Monitor
  import_tasks: delete_connector_monitor.yaml
  tags: delete_connector_monitor

- name: Create API Health Check Monitor
  import_tasks: create_api_healthcheck_monitor.yaml
  tags: create_api_healthcheck_monitor
  