##########################
##                      ##
## - Resume Connector - ##
##                      ##
##########################

- name: Resume Connector 
  include_tasks: tasks/resume_connector_block.yaml
  loop: 
    - JiraSourceConnector_0
    - ServiceNowSourceConnector_0
    # - ElasticsearchSinkConnector_0
